FlowerShop/Controllers/CategorieController.cs
using Boutique.Models;
using Boutique.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Boutique.Controllers
{
    [Authorize(Roles = ShopConstants.Admin)]
    public class CategorieController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategorieController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Categorie> objList = _db.Categorie;
            return View(objList);
        }
        //get-create
        public IActionResult Creeaza()
        {
            
            return View("Upsert", new Categorie());
        }

        //post-create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Creeaza(Categorie obj)
        {
            if (ModelState.IsValid)
            {
                _db.Categorie.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //get-edit
        public IActionResult Editeaza(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Categorie.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View("Upsert", obj);
        }

        //post-edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editeaza(Categorie obj)
        {
            if (ModelState.IsValid)
            {
                _db.Categorie.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //post-delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Sterge(int? id)
        {
            var obj = _db.Categorie.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Categorie.Remove(obj);
            _db.SaveChanges();
            return Json(new { status = 200 });
        }
    }
}

FlowerShop/Controllers/CosController.cs
using Boutique.Models;
using Boutique.Models.ViewModels;
using Boutique.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text;

namespace Boutique.Controllers
{
    [Authorize]
    public class CosController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        [BindProperty]
        public ProdusUtilizatorViewModel productUserViewModel { get; set; }
        public CosController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Cos> shoppingCartList = new();
            if (HttpContext.Session.Get<IEnumerable<Cos>>(ShopConstants.SessionCart) != null
                && HttpContext.Session.Get<IEnumerable<Cos>>(ShopConstants.SessionCart).Count() > 0)
            {
                shoppingCartList = HttpContext.Session.Get<IEnumerable<Cos>>(ShopConstants.SessionCart).ToList();
            }

            List<int> prodInCart = shoppingCartList.Select(i => i.ProductId).ToList();
            IEnumerable<Produs> productsList = _db.Produs.Where(u => prodInCart.Contains(u.Id));
            return View(productsList);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult IndexPost()
        {
            return RedirectToAction(nameof(Sumar));
        }

        public IActionResult Sumar()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            List<Cos> shoppingCartList = new();
            if (HttpContext.Session.Get<IEnumerable<Cos>>(ShopConstants.SessionCart) != null
                && HttpContext.Session.Get<IEnumerable<Cos>>(ShopConstants.SessionCart).Count() > 0)
            {
                shoppingCartList = HttpContext.Session.Get<IEnumerable<Cos>>(ShopConstants.SessionCart).ToList();
            }

            List<int> prodInCart = shoppingCartList.Select(i => i.ProductId).ToList();
            IEnumerable<Produs> productsList = _db.Produs.Where(u => prodInCart.Contains(u.Id));

            productUserViewModel = new()
            {
                Utilizator = _db.Utilizator.FirstOrDefault(u => u.Id == claim.Value),
                ListaProduse = productsList.ToList()

            };

            return View(productUserViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Sumar")]
        public async Task<IActionResult> SumarPost(ProdusUtilizatorViewModel productUserViewModel)
        {
            var PathToTemplate = _webHostEnvironment.WebRootPath + Path.DirectorySeparatorChar.ToString()
                  + "template" + Path.DirectorySeparatorChar.ToString() +
                  "Inquiry.html";
            var subject = "New";
            string HtmlBody = "";
            using (StreamReader sr = System.IO.File.OpenText(PathToTemplate))
            {
                HtmlBody = sr.ReadToEnd();
            }
            StringBuilder productListSB = new StringBuilder();
            foreach (var prod in productUserViewModel.ListaProduse)
            {
                productListSB.Append($" - Name: {prod.Name} <span style='font-size:14px;'> (ID: {prod.Id})</span><br />");
            }

            string messageBody = string.Format(HtmlBody,
                productUserViewModel.Utilizator.FullName,
                productUserViewModel.Utilizator.Email,
                productUserViewModel.Utilizator.PhoneNumber,
                productListSB.ToString());
            return RedirectToAction(nameof(ConfirmaTranzactia));
        }
        public IActionResult ConfirmaTranzactia()
        {
            HttpContext.Session.Clear();
            return View();
        }
        public IActionResult Sterge(int id)
        {
            List<Cos> shoppingCartList = new();
            if (HttpContext.Session.Get<IEnumerable<Cos>>(ShopConstants.SessionCart) != null
                && HttpContext.Session.Get<IEnumerable<Cos>>(ShopConstants.SessionCart).Count() > 0)
            {
                shoppingCartList = HttpContext.Session.Get<IEnumerable<Cos>>(ShopConstants.SessionCart).ToList();
            }
            shoppingCartList.Remove(shoppingCartList.FirstOrDefault(u => u.ProductId == id));
            HttpContext.Session.Set(ShopConstants.SessionCart, shoppingCartList);
            return RedirectToAction(nameof(Index));
        }
    }
}

FlowerShop/Controllers/ProdusController.cs
using Boutique.Models.ViewModels;
using Boutique.Models;
using Boutique.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Boutique.Controllers
{
    [Authorize(Roles = ShopConstants.Admin)]
    public class ProdusController : Controller
    {

        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment webHostEnvironment;

        public ProdusController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            this.webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            IEnumerable<Produs> objList = _db.Produs;
            foreach (var obj in objList)
            {
                obj.Categorie = _db.Categorie.FirstOrDefault(u => u.Id == obj.CategorieId);
            };
            return View(objList);
        }
        //get-upsert
        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            ProdusViewModel productViewModel = new()
            {
                Produs = new Produs(),
                CategoriaListaSelectabila = _db.Categorie.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()

                }),
            };


            if (id == null)
            {
                return View(productViewModel);
            }
            else
            {
                productViewModel.Produs = _db.Produs.Find(id);
                if (productViewModel.Produs == null)
                {
                    return NotFound();
                }
                return View(productViewModel);
            }
        }

        //post-upsert
        [HttpPost]
        public IActionResult Upsert(ProdusViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                string webRootPath = webHostEnvironment.WebRootPath;

                if (productViewModel.Produs.Id == -1)
                {
                    productViewModel.Produs.Id = 0;
                    string upload = webRootPath + ShopConstants.ImagePath;
                    string fileName = Guid.NewGuid().ToString();
                    string extention = Path.GetExtension(files[0].FileName);


                    using (var fileStream = new FileStream(Path.Combine(upload, fileName + extention), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    productViewModel.Produs.Image = fileName + extention;

                    _db.Produs.Add(productViewModel.Produs);
                }
                else
                {
                    var objFromBb = _db.Produs.AsNoTracking().FirstOrDefault(u => u.Id == productViewModel.Produs.Id);
                    if (files.Count > 0)
                    {
                        string upload = webRootPath + ShopConstants.ImagePath;
                        string fileName = Guid.NewGuid().ToString();
                        string extention = Path.GetExtension(files[0].FileName);
                        var oldFile = Path.Combine(upload, objFromBb.Image);
                        if (System.IO.File.Exists(oldFile))
                        {
                            System.IO.File.Delete(oldFile);
                        }
                        using (var fileStream = new FileStream(Path.Combine(upload, fileName + extention), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                        }
                        productViewModel.Produs.Image = fileName + extention;

                    }
                    else
                    {
                        productViewModel.Produs.Image = objFromBb.Image;
                    }
                    _db.Produs.Update(productViewModel.Produs);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            productViewModel.CategoriaListaSelectabila = _db.Categorie.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()

            });
            return View(productViewModel);
        }
        //post-delete
        [HttpPost]
        public async Task<ActionResult> Sterge(int? id)
        {
            Produs? obj = _db.Produs.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            string upload = webHostEnvironment.WebRootPath + ShopConstants.ImagePath;


            var oldFile = Path.Combine(upload, obj.Image);
            if (System.IO.File.Exists(oldFile))
            {
                System.IO.File.Delete(oldFile);
            }

            _db.Produs.Remove(obj);
            await _db.SaveChangesAsync();
            return Json(new { status = 200 });
        }
        [HttpGet]
        public async Task<IActionResult> InsertDataFromJson()
        {
            try
            {
                var filePath = Path.Combine(webHostEnvironment.WebRootPath, "data.json");

                if (!System.IO.File.Exists(filePath))
                {
                    return NotFound("JSON file not found");
                }
                var jsonData = await System.IO.File.ReadAllTextAsync(filePath);
                var products = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ProductData>>(jsonData);
                foreach (var productData in products)
                {
                    // Save image to server
                    var imageName = Guid.NewGuid().ToString() + ".jpg";
                    string upload = webHostEnvironment.WebRootPath + ShopConstants.ImagePath.Replace('\\', '/');
                    var imagePath = Path.Combine(upload, imageName);
                    using (var httpClient = new HttpClient())
                    using (var fileStream = new FileStream(imagePath, FileMode.Create))
                    {
                        var imageBytes = await httpClient.GetByteArrayAsync(productData.ImageUrl);
                        await fileStream.WriteAsync(imageBytes);
                    }
                    var category = await _db.Categorie.FirstOrDefaultAsync(c => c.Name == "123");
                    if (category == null)
                    {
                        category = new Categorie { Name = "Default" };
                        _db.Categorie.Add(category);
                        await _db.SaveChangesAsync(); // Save category changes
                    }

                    // Create product
                    var product = new Produs
                    {
                        Id = 0,
                        Name = productData.Title,
                        Description = "",
                        Price = productData.Price,
                        Image = imageName,
                        CategorieId = category.Id
                    };

                    _db.Produs.Add(product);
                    await _db.SaveChangesAsync();
                }
                return Ok("Data inserted successfully");
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"An error occurred while inserting data: {ex.Message}");
            }
        }
    }
}

FlowerShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor 
@using Boutique.Utility
<!DOCTYPE html>
<html lang="ro">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @ShopConstants.ShopName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawersome/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@ShopConstants.ShopName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex flex-md-row-reverse">
                  <partial name="_LoginPartial" />
                  <ul class="navbar-nav flex-grow-1">

                      <li class="nav-item">
                          <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Acasa</a>
                      </li>

                      @if (User.IsInRole(ShopConstants.Admin))
                      {
                          <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  Admin
                              </a>
                              <div class="dropdown-menu"  aria-labelledby="navbarDropdown">
                                  <a class="nav-link text-dark" asp-area="" asp-controller="Categorie" asp-action="Index">Categorie</a>
                                  <a class="nav-link text-dark" asp-area="" asp-controller="Produs" asp-action="Index">Produs</a>
                              </div>
                          </li>
                      }
                          <li>
                              @if (HttpContextAccessor.HttpContext.Session.Get<List<Cos>>(ShopConstants.SessionCart) != null)
                              {
                                  <a asp-action="Index" asp-controller="Cos" class="nav-link">
                                      @{ var count = HttpContextAccessor.HttpContext.Session.Get<List<Cos>>(ShopConstants.SessionCart).Count;}
                                      <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                  </a>
                              }
                              else
                              {
                                  <a href="#" class="nav-link">
                                      <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                  </a>
                              }
                          </li>
                      </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - @ShopConstants.ShopName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
   
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FlowerShop/Views/Shared/_ProductCard.cshtml
@model Boutique.Models.Produs
<div class="col-lg-3 col-md-6 pb-4 filter @Model.Categorie.Name.Replace(' ','_')">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border: 1px solid #222">
        <div class="card-body p-0 pb-1 text-center">
            <img class="card-img-top img-fluid d-block mb-3" src="@ShopConstants.ImagePath@Model.Image"
                alt="Imagine card" style="object-fit: cover; height: 200px; width: 100%;">
            <span class="h5">@Model.Name</span>
            <br>
            <span class="text-info h5">@string.Format("{0}", Model.Price) Lei</span>
        </div>
        <a asp-action="Detalii" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2 btn-detalii"
            style="height:40px; margin-top: 10px;">Vezi detalii</a>
    </div>
</div>

<style>
    .card-body {
        background-color: white;
        z-index: 1;
    }

    .card {
        position: relative;
    }

    .btn-detalii {
        position: absolute;
        z-index: 0;
        bottom: 0;
        left: 0;
        transform: translateY(0);
        transition: transform 0.3s ease-in-out;
    }

    .card:hover .btn-detalii {
        transform: translateY(125%);
    }
    .card:not(:hover) .btn-detalii {
        transition-delay: 250ms;
    }
</style>